export const dummyDataItems = [
  {
    id: 1,
    name: "user1",
    email: "user1@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 2,
    name: "user2",
    email: "user2@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 3,
    name: "user3",
    email: "user3@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 4,
    name: "user4",
    email: "user4@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 5,
    name: "user5",
    email: "user5@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 7,
    name: "user7",
    email: "user7@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 8,
    name: "user8",
    email: "user8@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 9,
    name: "user9",
    email: "user9@gmail.com",
    password: "12345",
    bg: "red",
  },
  {
    id: 10,
    name: "user10",
    email: "user10@gmail.com",
    password: "12345",
    bg: "red",
  },
];
